### ISSUE TITLE
please respect XDG configuration

### ISSUE THREAD

**Issue by ccoVeille** [jaytyrrell13/pal#4]
You are storing files in ~/.pal, it's OK, but it could be better.

You could respect the XDG basedir specification
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I would say, it should be either $XDG_DATA_HOME/pal/ or $XDG_CONFIG_HOME/pal/ instead of `~/.pal`

so on linux, something like that
- $XDG_DATA_HOME/pal/ => ~/.local/share/pal/
- $XDG_CONFIG_HOME/pal/ => ~/.config/pal/

I would say the config folder should be preferred, but any of XDG folder would be better than something in the home folder

So the `.pal` would become  `~/.config/pal/aliases` or something like that

Home folder should stay clean

You can look at tool such as this one, that promotes using the right folders for tools
https://github.com/doron-cohen/antidot

**Comment by ccoVeille** [comment]
I think it was done with 94f7a2b09c906ced7c641df604a5da153aaea71c, so outside PR process

but it's great

**Comment by jaytyrrell13** [comment]
Thanks for bringing this up! I agree the home directory should stay clean. I think moving `~/.pal` to the `.config` directory is a much better solution. Thanks again!
